### ISSUE TITLE
Canvas triggering error during build on Node >10

### ISSUE THREAD

**Issue by nick-myers-dt** [codecept-js/codeceptjs-resemblehelper#67]
When we include:
```
"codeceptjs-resemblehelper": "^1.9.0"
```
in our `package.json` and run `"codeceptjs": "^2.6.3"` test:
```
Feature("Home page");

Scenario("Search for something", (I) => {
  I.amOnPage("http://localhost:3000");
  I.fillField("Search", "Miles");
  I.click("Search");
  I.seeInCurrentUrl("/");
});

Scenario("Click on production link", (I) => {
  I.amOnPage("http://localhost:3000");
  I.click("The Link");
  I.seeInCurrentUrl("/link");
});

Scenario("Scroll to footer and click on privacy policy", (I) => {
  I.amOnPage("http://localhost:3000");
  I.scrollTo("footer");
  I.click("Privacy policy");
  I.seeInCurrentUrl("/privacy");
});
```
we get the following error:
```
error /home/node/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/node/node_modules/canvas
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@14.2.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/home/node/node_modules/canvas/build/Release/canvas.node" (not found)
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-musl-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-musl-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-musl-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.2.0 (node-v83 ABI, musl) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-musl-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.2.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.2.0 | linux | x64
gyp info find Python using Python version 3.8.2 found at "/usr/bin/python3"
gyp http GET https://unofficial-builds.nodejs.org/download/release/v14.2.0/node-v14.2.0-headers.tar.gz
gyp http 200 https://unofficial-builds.nodejs.org/download/release/v14.2.0/node-v14.2.0-headers.tar.gz
gyp http GET https://unofficial-builds.nodejs.org/download/release/v14.2.0/SHASUMS256.txt
gyp http 200 https://unofficial-builds.nodejs.org/download/release/v14.2.0/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/node/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/14.2.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/14.2.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/14.2.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/node/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
/bin/sh: pkg-config: not found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.76-linuxkit
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/node/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/node/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/node/node_modules/canvas
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/node/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/node/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/node/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.19.76-linuxkit
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/node/node_modules/canvas/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/node/node_modules/canvas
node-pre-gyp ERR! node -v v14.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/node/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/node/node_modules/canvas/build/Release --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

If we leave this helper package out, then codeceptjs reports the error:
```
$ npx codeceptjs run --reporter mocha-junit-reporter --steps --verbose
 
Could not load helper ResembleHelper from module 'codeceptjs-resemblehelper':
Cannot find module 'codeceptjs-resemblehelper'
``` 

We're not using the ResembleHelper in our tests, however it appears that without it, our codeceptjs tests will not work.

Any idea what we can do to remedy this?

**Comment by puneet0191** [comment]
Thanks a lot for the report @nick-myers-dt could check if you still have helper mentioned in the configuration file?

That node error seems to be related to canvas 2.6.1, may be you could try to update it to 2.6.2?

**Comment by nick-myers-dt** [comment]
Thank you @puneet0191 for replying.  You are correct, we do have the helper in the configuration file.  That will help us get past the build issue, many thanks!

In relation to the canvas version - I can only see 2.6.1 on https://github.com/Automattic/node-canvas/releases, is there a 2.6.2 release?

**Comment by nick-myers-dt** [comment]
By including the following in our Dockerfile, and installing the following packages to node:apline-latest we've been able to work around the error.

`RUN apk upgrade --update && apk add python3 curl tar autoconf g++ make cairo cairo-dev cairomm-dev libjpeg-turbo-dev pango pango-dev pangomm pangomm-dev giflib-dev pixman pixman-dev`

**Comment by puneet0191** [comment]
Thanks , closing the issue since it is mostly because of configuration file you see missing helper, also regarding canvas yes I meant 2.6.1 sorry I missed your point about, thanks for the workaround.
